export const country = [
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "BASIC countries (Brazil, South Africa, India and China)",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Alliance of Small Island States (AOSIS)",
    "Andorra",
    "Angola",
    "Anguilla",
    "Annex-I Parties to the Convention",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Aruba"];

export const sector = [
    "Agriculture",
    "Energy",
    "Total excluding LULUCF",
    "Waste",
    "Industrial Processes and Product Use",
    "Other",
    "Land Use, Land-Use Change and Forestry",
    "Total GHG emissions with LULUCF",
    "Total GHG emissions without LULUCF",
    "Transportation",
    "Electricity/Heat",
    "Land-Use Change and Forestry",
    "Manufacturing/Construction",
    "Total including LUCF",
    "Total excluding LUCF",
    "Industrial Processes",
    "Fugitive Emissions",
    "Other Fuel Combustion",
    "Total GHG emissions including LULUCF/LUCF",
    "Solvent and Other Product Use",
    "Bunker Fuels",
    "Total GHG emissions excluding LULUCF/LUCF"
];

export const gas = [
    "N2O",
    "KYOTOGHG",
    "F-Gases",
    "CH4",
    "CO₂",
    "Aggregate F-gases",
    "CO2",
    "All GHG",
    "F-Gas",
    "Aggregate GHGs",
    "CH₄",
    "N₂O"
]

export const unit = [
    "EJ/yr",
    "Mt CO2e/yr",
    "Mt/yr",
    "MtCO₂e",
    "US$2016/tCO2",
    "degree C",
    "billion US$2016/yr",
    "Million",
    "million Ha/yr"
]