# Generated by Django 2.2.7 on 2019-11-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='effecttype',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.Property'),
        ),
    ]
