# Generated by Django 2.2.7 on 2019-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0002_auto_20191117_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
