CREATE SCHEMA "public";

CREATE SEQUENCE "public".city_id_seq START WITH 1;

CREATE SEQUENCE "public".emission_emissionid_seq START WITH 1;

CREATE  TABLE "public".cat_country_pledges_csv ( 
	sector               varchar(23)  NOT NULL ,
	"indicator"          varchar(104)  NOT NULL ,
	unit                 varchar(45)  NOT NULL ,
	country              varchar(20)  NOT NULL ,
	"year"               integer  NOT NULL ,
	"variable"           varchar(36)  NOT NULL ,
	"value"              numeric(20,13)  NOT NULL ,
	label                varchar(255)   
 );

CREATE  TABLE "public".cdiac_fossil_fuel_cement_national_csv ( 
	nation               varchar(63)  NOT NULL ,
	"year"               varchar(20)  NOT NULL ,
	total                varchar(13)  NOT NULL ,
	solid_fuel           numeric(11,1)   ,
	liquid_fuel          numeric(10,1)   ,
	gas_fuel             numeric(10,1)   ,
	cement               numeric(7,1)  NOT NULL ,
	gas_flaring          numeric(9,1)   ,
	per_capita           numeric(6,2)   ,
	bunkers              numeric(6,1)  NOT NULL 
 );

CREATE  TABLE "public".cdp_2019_full_cities_dataset_csv ( 
	questionnaire        varchar(2048)   ,
	year_reported_to_cdp integer   ,
	account_number       integer   ,
	organization         varchar(2048)   ,
	country              varchar(2048)   ,
	cdp_region           varchar(2048)   ,
	parent_section       varchar(2048)   ,
	"section"            varchar(2048)   ,
	question_number      varchar(2048)   ,
	question_name        varchar(2048)   ,
	column_number        varchar(2048)   ,
	"column_name"        varchar(2048)   ,
	row_number           varchar(2048)   ,
	row_name             varchar(2048)   ,
	response_answer      varchar(2048)   ,
	comments             varchar(2048)   ,
	file_name            varchar(2048)   ,
	"last update"        varchar(2048)   
 );

CREATE  TABLE "public".city ( 
	cityid               bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	organization_name    varchar  NOT NULL ,
	country_name         varchar(2048)   ,
	CONSTRAINT city_pkey PRIMARY KEY ( cityid )
 );

CREATE  TABLE "public".consumption_emissions_csv ( 
	code                 varchar(28)  NOT NULL ,
	"year"               integer  NOT NULL ,
	consumption_emissions numeric(10,3)  NOT NULL 
 );

CREATE  TABLE "public".country ( 
	cld_rdisplayname     varchar(49)  NOT NULL ,
	capital              varchar(24)  NOT NULL ,
	continent            varchar(5)  NOT NULL ,
	ds                   varchar(5)  NOT NULL ,
	developed_developing_countries varchar(13)  NOT NULL ,
	dial                 varchar(22)  NOT NULL ,
	edgar                varchar(5)  NOT NULL ,
	fifa                 varchar(19)  NOT NULL ,
	fips                 varchar(33)  NOT NULL ,
	gaul                 varchar(7)  NOT NULL ,
	geoname_id           varchar(9)  NOT NULL ,
	global_code          varchar(5)  NOT NULL ,
	global_name          varchar(6)  NOT NULL ,
	ioc                  varchar(5)  NOT NULL ,
	is_o3166_1__alpha_2  varchar(5)  NOT NULL ,
	is_o3166_1__alpha_3  varchar(5)  NOT NULL ,
	is_o3166_1_numeric   varchar(5)  NOT NULL ,
	is_o4217_currency_alphabetic_code varchar(9)  NOT NULL ,
	is_o4217_currency_country_name varchar(67)  NOT NULL ,
	is_o4217_currency_minor_unit varchar(5)  NOT NULL ,
	is_o4217_currency_name varchar(37)  NOT NULL ,
	is_o4217_currency_numeric_code varchar(9)  NOT NULL ,
	itu                  varchar(5)  NOT NULL ,
	intermediate_region_code varchar(5)  NOT NULL ,
	intermediate_region_name varchar(19)  NOT NULL ,
	land_locked_developing_countries_lldc varchar(5)  NOT NULL ,
	languages            varchar(104)  NOT NULL ,
	least_developed_countries_ldc varchar(5)  NOT NULL ,
	m49                  varchar(5)  NOT NULL ,
	marc                 varchar(18)  NOT NULL ,
	region_code          varchar(5)  NOT NULL ,
	region_name          varchar(10)  NOT NULL ,
	small_island_developing_states_sids varchar(5)  NOT NULL ,
	sub_region_code      varchar(5)  NOT NULL ,
	sub_region_name      varchar(40)  NOT NULL ,
	tld                  varchar(5)  NOT NULL ,
	unterm_arabic_formal varchar(65)  NOT NULL ,
	unterm_arabic_short  varchar(65)  NOT NULL ,
	unterm_chinese_formal varchar(16)  NOT NULL ,
	unterm_chinese_short varchar(16)  NOT NULL ,
	unterm_english_formal varchar(72)  NOT NULL ,
	unterm_english_short varchar(75)  NOT NULL ,
	unterm_french_formal varchar(71)  NOT NULL ,
	unterm_french_short  varchar(72)  NOT NULL ,
	unterm_russian_formal varchar(75)  NOT NULL ,
	unterm_russian_short varchar(75)  NOT NULL ,
	unterm_spanish_formal varchar(65)  NOT NULL ,
	unterm_spanish_short varchar(67)  NOT NULL ,
	wmo                  varchar(5)  NOT NULL ,
	is_independent       varchar(28)  NOT NULL ,
	official_name_ar     varchar(65)  NOT NULL ,
	official_name_cn     varchar(16)  NOT NULL ,
	official_name_en     varchar(67)  NOT NULL ,
	official_name_es     varchar(65)  NOT NULL ,
	official_name_fr     varchar(66)  NOT NULL ,
	official_name_ru     varchar(75)  NOT NULL 
 );

CREATE  TABLE "public".cw_ndc_quantification_csv ( 
	iso                  varchar(5)  NOT NULL ,
	country              varchar(41)  NOT NULL ,
	"year"               integer  NOT NULL ,
	"value"              numeric(11,2)   ,
	range                varchar(2048)   ,
	label                varchar(31)  NOT NULL 
 );

CREATE  TABLE "public".cw_unfccc_ghg_emissions_csv ( 
	country              varchar(3)  NOT NULL ,
	sector               varchar(78)  NOT NULL ,
	gas                  varchar(41)  NOT NULL ,
	gwp                  varchar(3)  NOT NULL ,
	"1990"               varchar(15)   ,
	"1991"               varchar(15)   ,
	"1992"               varchar(15)   ,
	"1993"               varchar(15)   ,
	"1994"               varchar(15)   ,
	"1995"               varchar(15)   ,
	"1996"               varchar(15)   ,
	"1997"               varchar(15)   ,
	"1998"               varchar(15)   ,
	"1999"               varchar(15)   ,
	"2000"               varchar(15)   ,
	"2001"               varchar(15)   ,
	"2002"               varchar(15)   ,
	"2003"               varchar(15)   ,
	"2004"               varchar(15)   ,
	"2005"               varchar(15)   ,
	"2006"               varchar(15)   ,
	"2007"               varchar(15)   ,
	"2008"               varchar(15)   ,
	"2009"               varchar(15)   ,
	"2010"               varchar(15)   ,
	"2011"               varchar(15)   ,
	"2012"               varchar(15)   ,
	"2013"               varchar(15)   ,
	"2014"               varchar(15)   ,
	datasource           varchar(7)  NOT NULL ,
	last_reported_value  varchar(15)   
 );

CREATE  TABLE "public".emission ( 
	emissionid           bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	mmtco2e              numeric(16,10)  NOT NULL ,
	gas                  varchar(2048)   ,
	sector               varchar(2048)   ,
	last_reported_year   varchar(2024) DEFAULT 2015  ,
	country              char(3)   ,
	datasource           varchar(2048)   ,
	last_reported_mmtco2e numeric(16,10)   ,
	CONSTRAINT pk_emission_emissionid PRIMARY KEY ( emissionid )
 );

COMMENT ON COLUMN "public".emission.mmtco2e IS 'Million metric tons of carbon dioxide equivalencies';

COMMENT ON COLUMN "public".emission.last_reported_mmtco2e IS 'Last reported value of mmtco2e in the last year that it was reported';

CREATE  TABLE "public".pledge ( 
	country              char(2048)   ,
	pledgeyear           varchar(4)  NOT NULL ,
	pledgevalue          integer   ,
	pledgeindicator      varchar(2048)   ,
	unit                 varchar(2048)   ,
	sector               varchar(2048)   ,
	countryname          varchar(2048)   
 );

CREATE  TABLE "public".primap_hist_v2_0_11_dec_2018_csv ( 
	scenario             varchar(2048)   ,
	country              varchar(2048)   ,
	category             varchar(2048)   ,
	entity               varchar(2048)   ,
	unit                 varchar(2048)   ,
	latest_reported_value numeric(24,10)   
 );

