export const location = [
    "Africa", "Africa_Eastern"
];
export const scenario = [
    "Reference (2016)",
    "Evolving transition (ET)",
    "High Oil Price (2016)",
    "Low Economic growth (2016)",
    "High Economic growth (2016)",
    "Low Oil Price (2016)",
    "Low policy (2015)",
    "Paris - Increased ambition (2015)",
    "No policy (2015)"
];
export const indicator = [
    "Nuclear",
    "Total",
    "Gas",
    "Geothermal",
    "Oil",
    "GDP PPP",
    "GDP MER",
    "Coal",
    "Hydro",
    "Solar",
    "Wind",
    "Other",
    "Other Renewables",
    "Electricity",
    "CO2",
    "Coal w/o CCS",
    "Total carbon price",
    "Global Warming",
    "Solids",
    "Liquids",
    "Hydrogen",
    "Gases",
    "passenger",
    "freight",
    "Heat",
    "Natural Gas",
    "Transportation",
    "Land Use and Forestry",
    "Industry",
    "Fossil Fuel Consumption",
    "Buildings",
    "Fossil Fuels",
    "OC",
    "NOx",
    "Sulfur",
    "CO",
    "BC",
    "F-gases",
    "N2O",
    "CH4",
    "Biomass",
    "Oil w/ CCS",
    "Gas w/ CCS",
    "Coal w/ CCS",
    "Biomass w/ CCS",
    "Oil w/o CCS",
    "Gas w/o CCS",
    "Biomass w/o CCS",
    "Energy Crops",
    "Pasture",
    "Forest",
    "Cropland",
    "Energy Demand",
    "Energy Supply",
    "Solid Biomass w/ CCS",
    "Solid Biomass w/o CCS",
    "Liquefied Gas",
    "Liquefied Coal",
    "Liquefied Biomass",
    "Liquefied Fossil Fuels w/o CCS",
    "Liquefied Fossil Fuels w/ CCS",
    "Liquefied Fossil Fuels",
    "Liquefied Gas w/ CCS",
    "Liquefied Coal w/ CCS",
    "Liquefied Biomass w/ CCS",
    "Liquefied Gas w/o CCS",
    "Liquefied Coal w/o CCS",
    "Liquefied Biomass w/o CCS",
    "Liquid Derivative of Crude Oil",
    "Fossil w/o CCS",
    "Fossil w/ CCS",
    "Fossil"
];

export const unit = [
    "EJ/yr",
    "GW",
    "billion US$2016/yr",
    "Mt CO2e/yr",
    "Million",
    "US$2016/tCO2",
    "degree C",
    "Mt/yr",
    "million Ha/yr"
]
